# Create a denier that returns a google.rpc.Code 7 (PERMISSION_DENIED)
apiVersion: config.istio.io/v1alpha2
kind: denier
metadata:
  name: deny
  namespace: istio-system
spec:
  status:
    code: 7
    message: Not allowed
---
# The (empty) data handed to deny at run time
apiVersion: config.istio.io/v1alpha2
kind: checknothing
metadata:
  name: denyrequest
  namespace: istio-system
spec:
---
# The rule that uses denier to deny requests with destination == "emailservice.default.svc.cluster.local"
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: deny-emailservice-service
  namespace: istio-system
spec:
  match: destination.service=="emailservice.default.svc.cluster.local"
  actions: #then
  - handler: deny.denier
    instances:
    - denyrequest.checknothing
